# Boxed Configuration {$version}
boxed:
  command:
    # Player Command. What command users will run to access their area.
    # To define alias, just separate commands with white space.
    player: boxed bx box
    # The admin command.
    # To define alias, just separate commands with white space.
    admin: boxadmin
    # The default action for new player command call.
    # Sub-command of main player command that will be run on first player command call.
    # By default it is sub-command 'create'.
    new-player-action: create
    # The default action for player command.
    # Sub-command of main player command that will be run on each player command call.
    # By default it is sub-command 'go'.
    default-action: go
  # Announce advancements. We recommend you set the game rule `/gamerule announceAdvancements false`
  # but that blocks all new advancement announcements. This setting tells Boxed to broadcast new advancements.
  broadcast-advancements: false
world:
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: Boxed
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. boxed_world, boxed_world_nether, boxed_world_end)
  world-name: boxed_world
  # World seed.
  # If you change this, stop the server and delete the worlds made.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  seed: 978573758696
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: NORMAL
  spawn-limits:
    # Spawn limits. These override the limits set in bukkit.yml
    # If set to a negative number, the server defaults will be used
    monsters: -1
    animals: -1
    water-animals: -1
    ambient: -1
    # Setting to 0 will disable animal spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    ticks-per-animal-spawns: -1
    # Setting to 0 will disable monster spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    ticks-per-monster-spawns: -1
  # Radius of player areas. (So distance between player starting spots is twice this)
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  area-radius: 400
  # Starting size of boxed spaces. This is a radius so 1 = a 2x2 area.
  # Admins can adjust via the /boxadmin range set <player> <new range> command
  starting-protection-range: 1
  # Start to place players at these coordinates. This is where players will start in the
  # world. This must be a multiple of your area radius, but the plugin will auto
  # calculate the closest location on the grid. Players are placed around this location
  # in a spiral manner.
  # If none of this makes sense, leave it at 0,0.
  start-x: 0
  start-z: 0
  # Area height - Lowest is 5.
  # It is the y coordinate of the bedrock block in the blueprint.
  area-height: 5
  # Maximum number of player areas in the world. Set to -1 or 0 for unlimited.
  # If the number of areas is greater than this number, it will stop players from joining the world.
  max-areas: -1
  # The default game mode for this world. Players will be set to this mode when they create
  # a new area for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # The maximum number of players a player can ban at any one time in this game mode.
  # The permission boxed.ban.maxlimit.X where X is a number can also be used per player
  # -1 = unlimited
  ban-limit: -1
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    # Note: Some default challenges will not be possible if there is no nether.
    # Note that with a standard nether all players arrive at the same portal and entering a
    # portal will return them back to their areas.
    generate: true
    # Nether spawn protection radius - this is the distance around the nether spawn
    # that will be protected from player interaction (breaking blocks, pouring lava etc.)
    # Minimum is 0 (not recommended), maximum is 100. Default is 25.
    # Only applies to vanilla nether
    spawn-radius: 32
    # This option indicates if nether portals should be linked via dimensions.
    # Option will simulate vanilla portal mechanics that links portals together or creates a new portal,
    # if there is not a portal in other dimension.
    # Added since 1.0.3
    create-and-link-portals: true
  end:
    # End Nether - if this is false, the end world will not be made and access to
    # the end will not occur. Other plugins may still enable portal usage.
    generate: true
  # Mob white list - these mobs will NOT be removed when logging in or doing /boxed
  remove-mobs-whitelist: []
  # World flags. These are boolean settings for various flags for this world
  flags:
    HURT_ANIMALS: false
    DRAGON_EGG: false
    ISLAND_RESPAWN: true
    REDSTONE: true
    CREEPER_GRIEFING: true
    BUCKET: false
    ENDER_PEARL: false
    DOOR: true
    NATURAL_SPAWNING_OUTSIDE_RANGE: false
    BREAK_HOPPERS: false
    FURNACE: true
    LIQUIDS_FLOWING_OUT: true
    ANVIL: false
    MINECART: true
    FISH_SCOOPING: false
    END_PORTAL: false
    BREEDING: false
    ENDER_CHEST: false
    HURT_VILLAGERS: false
    TREES_GROWING_OUTSIDE_RANGE: true
    WITHER_DAMAGE: false
    FROST_WALKER: true
    TURTLE_EGGS: false
    PISTON_PUSH: false
    COLLECT_LAVA: false
    BREAK_SPAWNERS: false
    LEVER: false
    ELYTRA: true
    COARSE_DIRT_TILLING: true
    RIDING: false
    CAKE: false
    HURT_MONSTERS: true
    ARMOR_STAND: false
    NAME_TAG: false
    ENDERMAN_GRIEFING: true
    CLEAN_SUPER_FLAT: false
    TRADING: true
    EGGS: false
    ITEM_DROP: true
    NOTE_BLOCK: true
    ENTER_EXIT_MESSAGES: true
    FLINT_AND_STEEL: false
    NETHER_PORTAL: false
    REMOVE_END_EXIT_ISLAND: true
    LECTERN: false
    OFFLINE_GROWTH: true
    ITEM_PICKUP: true
    CROP_TRAMPLE: false
    BREWING: false
    DROPPER: false
    OBSIDIAN_SCOOPING: false
    CREEPER_DAMAGE: true
    TNT_PRIMING: false
    COLLECT_WATER: false
    GREENHOUSE: false
    BUTTON: false
    FIRE_EXTINGUISH: false
    COMMAND_RANKS: false
    BEACON: false
    TRAPDOOR: false
    EXPERIENCE_BOTTLE_THROWING: true
    PRESSURE_PLATE: false
    DYE: false
    ITEM_FRAME: false
    PLACE_BLOCKS: false
    CRAFTING: true
    REMOVE_MOBS: true
    ENCHANTING: true
    SHEARING: false
    BOAT: true
    BANK_ACCESS: false
    BED: false
    SPAWN_EGGS: false
    MILKING: false
    DISPENSER: false
    GATE: true
    CHEST_DAMAGE: true
    EXPERIENCE_PICKUP: true
    PREVENT_TELEPORT_WHEN_FALLING: false
    WORLD_TNT_DAMAGE: true
    HOPPER: false
    LEASH: false
    BREAK_BLOCKS: false
    MOUNT_INVENTORY: false
    OFFLINE_REDSTONE: true
    CHORUS_FRUIT: false
    CONTAINER: true
    ITEM_FRAME_DAMAGE: false
    JUKEBOX: false
    POTION_THROWING: true
    SPAWNER_SPAWN_EGGS: false
  # These are the default protection settings for new areas.
  # The value is the minimum area rank required allowed to do the action
  # Ranks are the following:
  #   VISITOR   = 0
  #   COOP      = 200
  #   TRUSTED   = 400
  #   MEMBER    = 500
  #   SUB-OWNER = 900
  #   OWNER     = 1000
  default-area-flags:
    HURT_ANIMALS: 500
    DRAGON_EGG: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 0
    BREAK_HOPPERS: 500
    FURNACE: 500
    MONSTER_SPAWNERS_SPAWN: 500
    ANVIL: 500
    MINECART: 500
    FISH_SCOOPING: 500
    FIRE_IGNITE: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    FROST_WALKER: 500
    TURTLE_EGGS: 500
    COLLECT_LAVA: 500
    BREAK_SPAWNERS: 500
    LEVER: 0
    ELYTRA: 0
    CAKE: 500
    RIDING: 500
    HURT_MONSTERS: 0
    NAME_TAG: 500
    ARMOR_STAND: 500
    TRADING: 0
    EGGS: 500
    ITEM_DROP: 0
    NOTE_BLOCK: 0
    FLINT_AND_STEEL: 500
    NETHER_PORTAL: 0
    LECTERN: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 0
    DROPPER: 500
    BREWING: 500
    TNT_PRIMING: 500
    COLLECT_WATER: 500
    BUTTON: 0
    FIRE_EXTINGUISH: 500
    COMMAND_RANKS: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 0
    EXPERIENCE_BOTTLE_THROWING: 500
    DYE: 500
    PLACE_BLOCKS: 500
    ITEM_FRAME: 500
    CRAFTING: 0
    SHEARING: 500
    ENCHANTING: 500
    ANIMAL_SPAWNERS_SPAWN: 500
    BOAT: 0
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 500
    DISPENSER: 500
    GATE: 0
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    BREAK_BLOCKS: 500
    MOUNT_INVENTORY: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    POTION_THROWING: 500
    JUKEBOX: 500
  # These are the default settings for new areas
  default-area-settings:
    PVP_END: false
    PVP_NETHER: false
    LEAF_DECAY: true
    TNT_DAMAGE: true
    MONSTER_SPAWNERS_SPAWN: true
    ANIMAL_NATURAL_SPAWN: true
    MONSTER_NATURAL_SPAWN: true
    FIRE_IGNITE: true
    FIRE_SPREAD: true
    FIRE_BURNING: true
    ANIMAL_SPAWNERS_SPAWN: true
    PVP_OVERWORLD: false
  # These settings/flags are hidden from users
  # Ops can toggle hiding in-game using SHIFT-LEFT-CLICK on flags in settings
  hidden-flags:
  - PVP_END
  - ANIMAL_NATURAL_SPAWN
  - ANIMAL_SPAWNERS_SPAWN
  - FIRE_IGNITE
  - FIRE_SPREAD
  - LEAF_DECAY
  - MONSTER_NATURAL_SPAWN
  - MONSTER_SPAWNERS_SPAWN
  - PVP_NETHER
  - PVP_OVERWORLD
  - TNT_DAMAGE
  - FIRE_BURNING
  - COLLECT_LAVA
  # Visitor banned commands - Visitors to areas cannot use these commands in this world
  visitor-banned-commands: []
  # Falling banned commands - players cannot use these commands when falling
  # if the PREVENT_TELEPORT_WHEN_FALLING world setting flag is active
  falling-banned-commands: []
area:
  # Default max team size
  # Permission size cannot be less than the default below. 
  max-team-size: 4
  # Default maximum number of coop rank members per area
  # Players can have the boxed.coop.maxsize.<number> permission to be bigger but
  # permission size cannot be less than the default below. 
  max-coop-size: 4
  # Default maximum number of trusted rank members per area
  # Players can have the boxed.trust.maxsize.<number> permission to be bigger but
  # permission size cannot be less than the default below. 
  max-trusted-size: 4
  # Default maximum number of homes a player can have. Min = 1
  # Accessed via /is sethome <number> or /is go <number>
  max-homes: 5
  reset:
    # How many resets a player is allowed (manage with /boxadmin reset add/remove/reset/set command)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 areas lifetime
    reset-limit: -1
    # Kicked or leaving players lose resets
    # Players who leave a team will lose an area reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # area by themselves and can only join a team.
    # Leave this true to avoid players exploiting free areas
    leavers-lose-reset: false
    # Allow kicked players to keep their inventory.
    # Overrides the on-leave inventory reset for kicked players.
    kicked-keep-inventory: false
    on-join:
      # What the addon should reset when the player joins or creates an area
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: true
      # Reset health - if true, the player's health will be reset.
      health: true
      # Reset hunger - if true, the player's hunger will be reset.
      hunger: true
      # Reset experience points - if true, the player's experience will be reset.
      exp: true
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
      # Reset advancements
      reset-advancements: true
      # Grant these advancements
      grant-advancements:
      - minecraft:story/root   
    on-leave:
      # What the plugin should reset when the player leaves or is kicked from an area
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: true
      # Reset health - if true, the player's health will be reset.
      health: false
      # Reset hunger - if true, the player's hunger will be reset.
      hunger: false
      # Reset experience - if true, the player's experience will be reset.
      exp: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
      # Reset advancements
      reset-advancements: false
      # Grant these advancements
      grant-advancements: []
  create-area-on-first-login:
    # Toggles the automatic area creation upon the player's first login on your server.
    # If set to true,
    #    * Upon connecting to your server for the first time, the player will be told that
    #     an area will be created for him.
    #   * Make sure you have a Blueprint Bundle called "default": this is the one that will
    #     be used to create the area.
    #   * An area will be created for the player without needing him to run the create command.
    # If set to false, this will disable this feature entirely.
    # Warning:
    #   * If you are running multiple gamemodes on your server, and all of them have
    #     this feature enabled, an area in all the gamemodes will be created simultaneously.
    #     However, it is impossible to know on which area the player will be teleported to afterwards.
    #   * Island creation can be resource-intensive, please consider the options below to help mitigate
    #     the potential issues, especially if you expect a lot of players to connect to your server
    #     in a limited period of time.
    enable: false
    # Time in seconds after the player logged in, before his area gets created.
    # If set to 0 or less, the area will be created directly upon the player's login.
    # It is recommended to keep this value under a minute's time.
    delay: 5
    # Toggles whether the area creation should be aborted if the player logged off while the
    # delay (see the option above) has not worn off yet.
    # If set to true,
    #   * If the player has logged off the server while the delay (see the option above) has not
    #     worn off yet, this will cancel the area creation.
    #   * If the player relogs afterward, since he will not be recognized as a new player, no area
    #     would be created for him.
    #   * If the area creation started before the player logged off, it will continue.
    # If set to false, the player's area will be created even if he went offline in the meantime.
    # Note this option has no effect if the delay (see the option above) is set to 0 or less.
    abort-on-logout: true
  # Toggles whether the player should be teleported automatically to his area when it is created.
  # If set to false, the player will be told his area is ready but will have to teleport to his area using the command.
  teleport-player-to-area-when-created: true
  # Create Nether or End areas if they are missing when a player goes through a portal.
  # Nether and End areas are usually pasted when a player makes their area, but if they are
  # missing for some reason, you can switch this on.
  # Note that bedrock removal glitches can exploit this option.
  create-missing-nether-end-areas: false
  commands:
    # List of commands to run when a player joins an area or creates one.
    # These commands are run by the console, unless otherwise stated using the [SUDO] prefix,
    # in which case they are executed by the player.
    # 
    # Available placeholders for the commands are the following:
    #    * [name]: name of the player
    # 
    # Here are some examples of valid commands to execute:
    #    * "[SUDO] bbox version"
    #    * "boxadmin deaths set [player] 0"
    on-join: []
    # List of commands to run when a player leaves an area, resets his area or gets kicked from it.
    # These commands are run by the console, unless otherwise stated using the [SUDO] prefix,
    # in which case they are executed by the player.
    # 
    # Available placeholders for the commands are the following:
    #    * [name]: name of the player
    # 
    # Here are some examples of valid commands to execute:
    #    * '[SUDO] bbox version'
    #    * 'boxadmin deaths set [player] 0'
    # 
    # Note that player-executed commands might not work, as these commands can be run with said player being offline.
    on-leave: []
    # Returns a list of commands that should be executed when the player respawns after death if Flags.ISLAND_RESPAWN is true.
    # These commands are run by the console, unless otherwise stated using the [SUDO] prefix,
    # in which case they are executed by the player.
    #
    # Available placeholders for the commands are the following:
    #    * [name]: name of the player
    #
    # Here are some examples of valid commands to execute:
    #    * '[SUDO] bbox version'
    #    * 'bsbadmin deaths set [player] 0'
    #
    # Note that player-executed commands might not work, as these commands can be run with said player being offline.
    # Added since 1.14.0.
    on-respawn: []
  sethome:
    nether:
      # Allow setting home in the nether. Only available on nether areas, not vanilla nether.
      allow: true
      require-confirmation: true
    the-end:
      # Allow setting home in the end. Only available on end areas, not vanilla end.
      allow: true
      require-confirmation: true
  deaths:
    # Whether deaths are counted or not.
    counted: true
    # Maximum number of deaths to count. The death count can be used by add-ons.
    max: 10
    # When a player joins a team, reset their death count
    team-join-reset: true
    # Reset player death count when they start a new area or reset an area
    reset-on-new-area: true
protection:
  # Geo restrict mobs.
  # Mobs that exit the area space where they were spawned will be removed.
  geo-limit-settings: []
  # Boxed blocked mobs.
  # List of mobs that should not spawn in Boxed.
  block-mobs: []
  # Invincible visitors. List of damages that will not affect visitors.
  # Make list blank if visitors should receive all damages
  invincible-visitors: []
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
